### ISSUE TITLE
Questions from previous week being carried over

### ISSUE THREAD

**Issue by BlackPanther112358** [Caffeinated-Typists/Leetcode-Automations#11]
When the tally reset has occurred, the scraper still scrapes problems from last 5 hours and thus problems from previous week are added to the fresh sheet.

**Comment by BlackPanther112358** [comment]
@Anirudh-S-Kumar, Do you have any approach to implement this other than putting a limit to not check submissions before Monday 12a.m. ?

**Comment by Anirudh-S-Kumar** [comment]
That's one possible way to do it. Other way maybe to change how we schedule the cron job, but I think questions might get skipped. 

We can increase the frequency of the cron jobs to maybe every 10 minutes and put time delta to 1 hour to minimise repetitions

**Comment by Anirudh-S-Kumar** [comment]
Yea repetitions may still happen I get that. It will have to be your approach then, cuz there's really no other way. We can't rely on GH actions to execute everytime accurately, so we can't totally rely on that for getting the correct questions

**Comment by BlackPanther112358** [comment]
Ok, I will implement it then

**Comment by BlackPanther112358** [comment]
Pushed the fix, will close the issue once we are sure that the script works
