### ISSUE TITLE
Root directory unorganized

### ISSUE THREAD

**Issue by Zynade** [Caffeinated-Typists/Leetcode-Automations#9]
idea: organize the directory structure of the program. 

1. IMO the root directory should contain only the following: README, LICENSE, .gitignore and requirements.txt. 
2. Put the python source code files in a src directory

**Comment by BlackPanther112358** [comment]
I tried this but geckodriver.exe has some permission issues then, and the Scraper script needs to be in the same file as that. So I ended up ditching this idea

**Comment by BlackPanther112358** [comment]
@Anirudh-S-Kumar  do you have anything to add else I am closing this issue

**Comment by Anirudh-S-Kumar** [comment]
I don't have anything else to add

**Comment by Anirudh-S-Kumar** [comment]
I don't have anything else to add

**Comment by Anirudh-S-Kumar** [comment]
Improved in commit bc8b752242fb5e95a241f4d777bfe049ed2acba1 , although it's still not perfect
